### ISSUE TITLE
[DOCS] Better options documentaion 

### ISSUE THREAD

**Issue by vahnag** [developit/decko#1]
These things are unclear from the current documentation about the options:
- How to use options
- What are the default values

It is possible to look them up in source code, but I think, it would be nice to have them in docs.

**Comment by developit** [comment]
The default values are specified after the colon in the readme: `delay: 0` or `cache: {}`.  This could certainly be clearer, though.  Good point about actual usage though, that is missing entirely.  They all follow the same pattern (`@foo(options)`), but it's probably worth just showing it explicitly for each.
