### ISSUE TITLE
TS definitions

### ISSUE THREAD

**Issue by Hotell** [developit/decko#5]
hey Jason. Would you be open to add TS definitions  for this project? If yes I'll sent PR.

thanks man!

**Comment by developit** [comment]
Sure! I didn't realize TS supported decorators! haha.  Just a .tsd you mean? I'm down.

**Comment by Hotell** [comment]
Can we get new release pls ? 🍻

**Comment by developit** [comment]
whoops! meant to Friday, just saw the todo list item

**Comment by developit** [comment]
released as 1.2.0 :)
